=== fowlie/keyboardbuilders/keyboards.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "KeyboardBuilders index",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "name",
      "repo",
      "image",
      "form_factors",
      "firmware_targets",
      "mcu"
    ],
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1
      },
      "repo": {
        "type": "string",
        "format": "uri"
      },
      "image": {
        "type": "string",
        "format": "uri"
      },
      "form_factors": {
        "type": "array",
        "items": {
          "enum": [
            "split",
            "unibody",
            "splay",
            "concave",
            "tilt"
          ]
        },
        "uniqueItems": true,
        "minItems": 0
      },
      "keys": {
        "type": [
          "integer",
          "null"
        ],
        "minimum": 10,
        "maximum": 120
      },
      "mcu": {
        "enum": [
          "ATmega32U4",
          "Adafruit Feather nRF52 Bluefruit",
          "Blackpill",
          "Pico",
          "Pro Micro",
          "RP2040 Zero",
          "RP2040",
          "Teensy 2.0",
          "nice!nano",
          "Xiao BLE"
        ]
      },
      "firmware_targets": {
        "type": "array",
        "items": {
          "enum": [
            "Absolem",
            "Atreus",
            "BlueMicro",
            "VIA",
            "Vial",
            "QMK",
            "ZMK",
            "KMK"
          ]
        },
        "minItems": 1,
        "uniqueItems": true
      },
      "last_updated": {
        "type": "string",
        "format": "date"
      }
    }
  }
}

=== fowlie/keyboardbuilders/keyboards.json
[
  {
    "name": "3W6",
    "repo": "https://github.com/weteor/3W6",
    "image": "https://raw.githubusercontent.com/weteor/3W6/main/images/3w6_rev2_1s.jpg",
    "form_factors": [
      "split"
    ],
    "keys": 36,
    "mcu": "ATmega32U4",
    "firmware_targets": [
      "QMK"
    ],
    "last_updated": "2025-08-12"
  },
  {
    "name": "Absolem",
    "repo": "https://github.com/mrzealot/absolem",
    "image": "https://zealot.hu/absolem/pics/splash.jpg",
    "form_factors": [
      "split",
      "unibody"
    ],
    "keys": 36,
    "mcu": "Adafruit Feather nRF52 Bluefruit",
    "firmware_targets": [
      "Absolem"
    ],
    "last_updated": "2025-08-12"
  },
  {
    "name": "Architeuthis dux",
    "repo": "https://github.com/tapioki/cephalopoda/tree/main/Architeuthis%20dux",
    "image": "https://raw.githubusercontent.com/tapioki/cephalopoda/main/Images/architeuthis_dux.png",
    "form_factors": [
      "splay",
      "split"
    ],
    "keys": 34,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-08-09"
  },
  {
    "name": "Atreus",
    "repo": "https://github.com/ckhroulev/atreus",
    "image": "https://github.com/ckhroulev/atreus/raw/master/atreus.jpg",
    "form_factors": [
      "split",
      "unibody"
    ],
    "keys": 42,
    "mcu": "Teensy 2.0",
    "firmware_targets": [
      "Atreus"
    ],
    "last_updated": "2025-08-12"
  },
  {
    "name": "Balbuzard",
    "repo": "https://github.com/brow/balbuzard",
    "image": "https://github.com/brow/balbuzard/raw/main/images/0.2_smores.jpg",
    "form_factors": [
      "split"
    ],
    "keys": 38,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK"
    ],
    "last_updated": "2025-08-12"
  },
  {
    "name": "Cantor-remix",
    "repo": "https://github.com/nilokr/cantor-remix",
    "image": "https://raw.githubusercontent.com/nilokr/cantor-remix/main/assets/cantor-remix.jpg",
    "form_factors": [
      "split"
    ],
    "keys": 36,
    "mcu": "Blackpill",
    "firmware_targets": [
      "QMK"
    ],
    "last_updated": "2025-08-12"
  },
  {
    "name": "Cheapino",
    "repo": "https://github.com/tompi/cheapino",
    "image": "https://raw.githubusercontent.com/tompi/cheapino/master/doc/gallery/27.png",
    "form_factors": [
      "split"
    ],
    "keys": 36,
    "mcu": "RP2040 Zero",
    "firmware_targets": [
      "QMK"
    ],
    "last_updated": "2025-08-09"
  },
  {
    "name": "Chocofi",
    "repo": "https://github.com/pashutk/chocofi",
    "image": "https://raw.githubusercontent.com/pashutk/chocofi/main/images/IMG_7067.jpeg",
    "form_factors": [
      "split"
    ],
    "keys": 36,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-08-09"
  },
  {
    "name": "Claw44",
    "repo": "https://github.com/yfuku/claw44",
    "image": "https://camo.githubusercontent.com/e10b21de4f3c442b8f8f7ce0b6d505586c8a82cbe9ce08ad7eb225e44dac548d/68747470733a2f2f692e696d6775722e636f6d2f356138696f676c2e6a7067",
    "form_factors": [
      "split"
    ],
    "keys": 44,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK"
    ],
    "last_updated": "2025-08-12"
  },
  {
    "name": "Clog V2",
    "repo": "https://github.com/smores56/clog-v2",
    "image": "https://github.com/smores56/clog-v2/raw/main/pictures/clog-v2-left-half.jpg",
    "form_factors": [
      "split",
      "splay"
    ],
    "keys": 34,
    "mcu": "Xiao BLE",
    "firmware_targets": [
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "Corne",
    "repo": "https://github.com/foostan/crkbd",
    "image": "https://github.com/foostan/crkbd/assets/736191/bc32e4e8-f737-4516-b92b-55a7cb93a336",
    "form_factors": [
      "split"
    ],
    "keys": 42,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-08-09"
  },
  {
    "name": "CRBN-Featherlight",
    "repo": "https://github.com/PolarityWorks/CRBN-Featherlight",
    "image": "https://camo.githubusercontent.com/eb292fbcce56ab1cbdd6225248de69ea7e9da46122953771b4c908dfd0926b4e/68747470733a2f2f692e696d6775722e636f6d2f474655534a53452e6a7067",
    "form_factors": [
      "unibody"
    ],
    "keys": 47,
    "mcu": "Elite-C",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "CrowBoard",
    "repo": "https://github.com/doesntfazer/CrowBoard",
    "image": "https://camo.githubusercontent.com/7cb8009db27872ff568c2b21fbb162abd1c2de3d422361371d8bb5a62adc7e48/68747470733a2f2f692e696d6775722e636f6d2f526737495950772e6a7067",
    "form_factors": [
      "split",
      "unibody"
    ],
    "keys": 36,
    "mcu": "Pico",
    "firmware_targets": [
      "QMK"
    ],
    "last_updated": "2025-08-09"
  },
  {
    "name": "Eek_doc",
    "repo": "https://github.com/Klackygears/eek_doc",
    "image": "https://camo.githubusercontent.com/b27663eb815b10f54dc501e85662baeb89da2ddc24dbbed740c6da782147b182/68747470733a2f2f692e696d6775722e636f6d2f33344f33784b572e6a7067",
    "form_factors": [
      "split"
    ],
    "keys": 36,
    "mcu": "Elite-C",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "Elephant42",
    "repo": "https://github.com/illness072/elephant42",
    "image": "https://raw.githubusercontent.com/illness072/elephant42/master/what-is-this.jpg",
    "form_factors": [
      "split"
    ],
    "keys": 42,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "ErgoDash",
    "repo": "https://github.com/omkbd/ErgoDash",
    "image": "https://raw.githubusercontent.com/omkbd/picture/master/Ergodash.jpg",
    "form_factors": [
      "split"
    ],
    "keys": 70,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "Eternal-keypad",
    "repo": "https://github.com/duckyb/eternal-keypad",
    "image": "https://user-images.githubusercontent.com/27895007/167808526-7cf01c83-1738-40c4-bed5-d04d67a561a3.png",
    "form_factors": [
      "unibody"
    ],
    "keys": 36,
    "mcu": "Elite-C",
    "firmware_targets": [
      "VIA",
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "Fourier",
    "repo": "https://github.com/keebio/fourier",
    "image": "https://cdn.shopify.com/s/files/1/1851/5125/products/image_1d38793c-ebb6-4df8-bab5-933162628fe5_1024x1024@2x.jpg",
    "form_factors": [
      "split"
    ],
    "keys": 47,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "Helix",
    "repo": "https://github.com/MakotoKurauchi/helix",
    "image": "https://camo.githubusercontent.com/257b75a0cb959884f1c9edff0b8f5b93b6515854c3cee51bf409e38e6932dd34/68747470733a2f2f692e696d6775722e636f6d2f5842416d796e4e2e6a7067",
    "form_factors": [
      "split"
    ],
    "keys": 64,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "Hummingbird",
    "repo": "https://github.com/PJE66/hummingbird",
    "image": "https://github.com/PJE66/hummingbird/raw/main/Images/Hummingbird_Top.png",
    "form_factors": [
      "split",
      "unibody"
    ],
    "keys": 30,
    "mcu": "Xiao BLE",
    "firmware_targets": [
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "Jian-Info",
    "repo": "https://github.com/KGOH/Jian-Info",
    "image": "https://camo.githubusercontent.com/3fb3fe801b8468cd08bbad750ba4b1c97ba50d36413aafe87953b8eb4f977c83/68747470733a2f2f692e696d6775722e636f6d2f6953334962486b2e6a7067",
    "form_factors": [
      "split"
    ],
    "keys": 44,
    "mcu": "ATmega32U4",
    "firmware_targets": [
      "QMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "Jorne",
    "repo": "https://github.com/joric/jorne",
    "image": "https://raw.githubusercontent.com/joric/jorne/jorne/images/jorne.jpg",
    "form_factors": [
      "split",
      "tilt"
    ],
    "keys": 44,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
    "name": "Kyria",
    "repo": "https://github.com/splitkb/kyria",
    "image": "https://splitkb.com/cdn/shop/files/HalcyonKyria1_924x616.jpg?v=1744190834",
    "form_factors": [
      "split"
    ],
    "keys": 50,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-08-09"
  },
  {
    "name": "LambBT",
    "repo": "https://github.com/johnlamb/LambBT",
    "image": "https://raw.githubusercontent.com/johnlamb/LambBT/main/images/lambbt.jpeg",
    "form_factors": [
      "splay",
      "split"
    ],
    "keys": 34,
    "mcu": "nice!nano",
    "firmware_targets": [
      "ZMK"
    ],
    "last_updated": "2025-08-09"
  },
  {
    "name": "Lily58",
    "repo": "https://github.com/kata0510/Lily58",
    "image": "https://user-images.githubusercontent.com/6285554/84393842-13960900-ac37-11ea-811e-65db2948ca73.jpg",
    "form_factors": [
      "split"
    ],
    "keys": 58,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-08-09"
  },
  {
    "name": "Lotus-58-Classic",
    "repo": "https://github.com/TweetyDaBird/Lotus-58-Classic",
    "image": "https://camo.githubusercontent.com/e7fa8018d3ec813a5c1524e9e2533565548a6016ae92dc3a0cc7bdcb470877ec/68747470733a2f2f707265766965772e726564642e69742f376170676f6d793637716636312e6a70673f77696474683d3430333226666f726d61743d706a7067266175746f3d7765627026733d63653166303435333339313439613939333131353832643434623435386338386332623136376133",
    "form_factors": [
      "split"
    ],
    "keys": 58,
    "mcu": "Pro Micro",
    "firmware_targets": [
      "QMK",
      "ZMK"
    ],
    "last_updated": "2025-09-03"
  },
  {
